# Generated by Django 5.2 on 2025-06-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="blood_type",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="height",
        ),
        migrations.AddField(
            model_name="profile",
            name="academic_year",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="العام الدراسي"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="major",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="التخصص"
            ),
        ),
    ]
