# Generated by Django 5.2 on 2025-06-27 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_confidencetestresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("motivation_choices", models.JSONField()),
                ("other_motivation", models.TextField(blank=True)),
                ("has_confidence_issues", models.BooleanField()),
                ("confidence_issues", models.JSONField(blank=True, null=True)),
                ("other_issues", models.TextField(blank=True)),
                ("expectations", models.JSONField()),
                ("other_expectations", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
