# Generated by Django 5.2 on 2025-09-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_achievement_userachievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="نبذة تعريفية"),
        ),
        migrations.AddField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "ذكر"), ("female", "أنثى")],
                max_length=10,
                null=True,
                verbose_name="الجنس",
            ),
        ),
    ]
